### ISSUE TITLE
bcrypt error in node@8.9.0

### ISSUE THREAD

**Issue by vjpr** [w3tecch/express-typescript-boilerplate#142]
What version of node do you use?

I encountered an error when using node@8.9.0.

```
$ yarn start db.seed

dyld: lazy symbol binding failed: Symbol not found: __ZN4node19GetCurrentEventLoopEPN2v87IsolateE
  Referenced from: xxx/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN4node19GetCurrentEventLoopEPN2v87IsolateE
  Referenced from: xxx/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  Expected in: flat namespace
```

I see that bcrypt 3 is being used.

```
"bcrypt": "^3.0.3",
```

I have found that bcrypt@3 doesn't work with 8.9.0 (even though bcrypt compatibility says `>=`)

https://github.com/kelektiv/node.bcrypt.js#version-compatibility

**Comment by benjlevesque** [comment]
I've also encountered issues with bcrypt, to build the docker image... this solved my issue https://stackoverflow.com/a/29320712
